# Generated by Django 5.2.13 on 2026-04-14 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportrequest',
            name='google_maps_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='supportrequest',
            name='request_type',
            field=models.CharField(choices=[('halal_food', "I can't find halal food"), ('recovery_kit', 'I need a recovery kit'), ('luggage_help', "I can't move with my luggage"), ('show_me_around', 'Talk with a local')], max_length=32),
        ),
    ]
