# Generated by Django 5.2.13 on 2026-04-14 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0002_supportrequest_google_maps_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportrequest',
            name='people',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
