# Generated by Django 5.2.13 on 2026-04-19 13:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0003_supportrequest_people'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportrequest',
            name='customer_name',
            field=models.CharField(default='unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='supportrequest',
            name='area',
            field=models.CharField(choices=[('ueno', 'Ueno'), ('akihabara', 'Akihabara'), ('yushima', 'Yushima'), ('asakusa', 'Asakusa')], max_length=32),
        ),
        migrations.AlterField(
            model_name='supportrequest',
            name='category',
            field=models.CharField(choices=[('service', 'Service'), ('experience', 'Experience')], editable=False, max_length=32),
        ),
        migrations.AlterField(
            model_name='supportrequest',
            name='request_type',
            field=models.CharField(choices=[('luggage_help', 'Luggage transfer'), ('show_me_around', 'Walk & talk in Tokyo')], max_length=32),
        ),
        migrations.CreateModel(
            name='SupportRequestChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('operator_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('support_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chat_room', to='requests_app.supportrequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportRequestChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('customer', 'Customer'), ('operator', 'Operator'), ('system', 'System')], max_length=20)),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('location', 'Location'), ('photo', 'Photo'), ('system', 'System')], default='text', max_length=20)),
                ('message', models.TextField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('google_maps_url', models.URLField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='chat_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chat_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='requests_app.supportrequestchatroom')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
