# Generated by Django 5.2.13 on 2026-04-22 05:56

import requests_app.models
import requests_app.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0004_supportrequest_customer_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportrequestchatmessage',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=requests_app.storage_backends.ChatImageStorage(), upload_to=requests_app.models.chat_image_upload_to),
        ),
    ]
